// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.newslettersender.domain;

import org.springframework.beans.factory.annotation.Configurable;
import si.kcclass.newslettersender.domain.AdvertiserIntegrationTest;

privileged aspect AdvertiserIntegrationTest_Roo_Configurable {
    
    declare @type: AdvertiserIntegrationTest: @Configurable;
    
}
