// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.newslettersender.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import si.kcclass.newslettersender.domain.Advertiser;
import si.kcclass.newslettersender.domain.AdvertiserDataOnDemand;

privileged aspect AdvertiserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdvertiserDataOnDemand: @Component;
    
    private Random AdvertiserDataOnDemand.rnd = new SecureRandom();
    
    private List<Advertiser> AdvertiserDataOnDemand.data;
    
    public Advertiser AdvertiserDataOnDemand.getNewTransientAdvertiser(int index) {
        Advertiser obj = new Advertiser();
        setEnabled(obj, index);
        setPassword(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void AdvertiserDataOnDemand.setEnabled(Advertiser obj, int index) {
        Boolean enabled = Boolean.TRUE;
        obj.setEnabled(enabled);
    }
    
    public void AdvertiserDataOnDemand.setPassword(Advertiser obj, int index) {
        String password = "password_" + index;
        if (password.length() > 100) {
            password = password.substring(0, 100);
        }
        obj.setPassword(password);
    }
    
    public void AdvertiserDataOnDemand.setUsername(Advertiser obj, int index) {
        String username = "username_" + index;
        if (username.length() > 50) {
            username = username.substring(0, 50);
        }
        obj.setUsername(username);
    }
    
    public Advertiser AdvertiserDataOnDemand.getSpecificAdvertiser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Advertiser obj = data.get(index);
        Long id = obj.getId();
        return Advertiser.findAdvertiser(id);
    }
    
    public Advertiser AdvertiserDataOnDemand.getRandomAdvertiser() {
        init();
        Advertiser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Advertiser.findAdvertiser(id);
    }
    
    public boolean AdvertiserDataOnDemand.modifyAdvertiser(Advertiser obj) {
        return false;
    }
    
    public void AdvertiserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Advertiser.findAdvertiserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Advertiser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Advertiser>();
        for (int i = 0; i < 10; i++) {
            Advertiser obj = getNewTransientAdvertiser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
