// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.newslettersender.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import si.kcclass.newslettersender.domain.SecurityRole;
import si.kcclass.newslettersender.domain.SecurityRoleDataOnDemand;

privileged aspect SecurityRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SecurityRoleDataOnDemand: @Component;
    
    private Random SecurityRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<SecurityRole> SecurityRoleDataOnDemand.data;
    
    public SecurityRole SecurityRoleDataOnDemand.getNewTransientSecurityRole(int index) {
        SecurityRole obj = new SecurityRole();
        setName(obj, index);
        return obj;
    }
    
    public void SecurityRoleDataOnDemand.setName(SecurityRole obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public SecurityRole SecurityRoleDataOnDemand.getSpecificSecurityRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SecurityRole obj = data.get(index);
        Long id = obj.getId();
        return SecurityRole.findSecurityRole(id);
    }
    
    public SecurityRole SecurityRoleDataOnDemand.getRandomSecurityRole() {
        init();
        SecurityRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SecurityRole.findSecurityRole(id);
    }
    
    public boolean SecurityRoleDataOnDemand.modifySecurityRole(SecurityRole obj) {
        return false;
    }
    
    public void SecurityRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SecurityRole.findSecurityRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SecurityRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SecurityRole>();
        for (int i = 0; i < 10; i++) {
            SecurityRole obj = getNewTransientSecurityRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
