// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.newslettersender.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import si.kcclass.newslettersender.domain.Subscriber;
import si.kcclass.newslettersender.domain.SubscriberDataOnDemand;
import si.kcclass.newslettersender.domain.SubscriberIntegrationTest;

privileged aspect SubscriberIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubscriberIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubscriberIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SubscriberIntegrationTest: @Transactional;
    
    @Autowired
    private SubscriberDataOnDemand SubscriberIntegrationTest.dod;
    
    @Test
    public void SubscriberIntegrationTest.testCountSubscribers() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = Subscriber.countSubscribers();
        Assert.assertTrue("Counter for 'Subscriber' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubscriberIntegrationTest.testFindSubscriber() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = Subscriber.findSubscriber(id);
        Assert.assertNotNull("Find method for 'Subscriber' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Subscriber' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubscriberIntegrationTest.testFindAllSubscribers() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = Subscriber.countSubscribers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Subscriber', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Subscriber> result = Subscriber.findAllSubscribers();
        Assert.assertNotNull("Find all method for 'Subscriber' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Subscriber' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubscriberIntegrationTest.testFindSubscriberEntries() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = Subscriber.countSubscribers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Subscriber> result = Subscriber.findSubscriberEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Subscriber' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Subscriber' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubscriberIntegrationTest.testFlush() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = Subscriber.findSubscriber(id);
        Assert.assertNotNull("Find method for 'Subscriber' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySubscriber(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Subscriber' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubscriberIntegrationTest.testMergeUpdate() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = Subscriber.findSubscriber(id);
        boolean modified =  dod.modifySubscriber(obj);
        Integer currentVersion = obj.getVersion();
        Subscriber merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Subscriber' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubscriberIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        Subscriber obj = dod.getNewTransientSubscriber(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Subscriber' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Subscriber' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubscriberIntegrationTest.testRemove() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = Subscriber.findSubscriber(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Subscriber' with identifier '" + id + "'", Subscriber.findSubscriber(id));
    }
    
}
