insert into kcclass_newsletter_sender.security_role(id, name, version) values (1, 'administrator', 0)
insert into kcclass_newsletter_sender.security_role(id, name, version) values (2, 'user', 0)
insert into kcclass_newsletter_sender.advertiser(id, username, password, enabled, email, version) values (1, 'marko', MD5('novak'), true, 'nouvak.kcclass@gmail.com', 0)
insert into kcclass_newsletter_sender.advertiser(id, username, password, enabled, email, version) values (2, 'janez', MD5('novak'), true, 'nouvak.kcclass@gmail.com', 0)
insert into kcclass_newsletter_sender.advertiser_roles(advertiser, roles) values (1, 1)
insert into kcclass_newsletter_sender.advertiser_roles(advertiser, roles) values (2, 2)
insert into kcclass_newsletter_sender.subscriber(id, name, surname, email, advertiser, version) values (1, 'test', 'subscriber', 'nouvak@gmail.com', 1, 0)