// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.newslettersender.domain;

import si.kcclass.newslettersender.domain.SecurityRole;

privileged aspect SecurityRole_Roo_JavaBean {
    
    public String SecurityRole.getName() {
        return this.name;
    }
    
    public void SecurityRole.setName(String name) {
        this.name = name;
    }
    
}
